service: intermediario
# app and org for use with dashboard.serverless.com
app: api

#useDotenv: true
#configValidationMode: off

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  profile: default
  #versionFunctions: false
  #lambdaHashingVersion: 20210924

functions:
  api:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
